//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereToBuy.web.App.Catalogs.Catalogs {
    
    
    public partial class Catalogs {
        
        /// <summary>
        /// CatalogsUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WhereToBuy.web.UserControls.Catalogs.Catalogs.CatalogsUC CatalogsUC;
    }
}
