//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação externa ativa.
        /// </summary>
        internal static string ActiveExternalInformationString {
            get {
                return ResourceManager.GetString("ActiveExternalInformationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso online ativo.
        /// </summary>
        internal static string ActiveOnlineAccessString {
            get {
                return ResourceManager.GetString("ActiveOnlineAccessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        internal static string ActiveString {
            get {
                return ResourceManager.GetString("ActiveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação de produtos automático.
        /// </summary>
        internal static string ActomaticProductCreationString {
            get {
                return ResourceManager.GetString("ActomaticProductCreationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada.
        /// </summary>
        internal static string AddressString {
            get {
                return ResourceManager.GetString("AddressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string AdministratorString {
            get {
                return ResourceManager.GetString("AdministratorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string AllString {
            get {
                return ResourceManager.GetString("AllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        internal static string AtiveString {
            get {
                return ResourceManager.GetString("AtiveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automático.
        /// </summary>
        internal static string AutomaticString {
            get {
                return ResourceManager.GetString("AutomaticString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível de disponibilidade.
        /// </summary>
        internal static string AvailabilityLevelString {
            get {
                return ResourceManager.GetString("AvailabilityLevelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        internal static string BackwardString {
            get {
                return ResourceManager.GetString("BackwardString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booleano incongruente com.
        /// </summary>
        internal static string BooleanInconsistentString {
            get {
                return ResourceManager.GetString("BooleanInconsistentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite.
        /// </summary>
        internal static string BoundString {
            get {
                return ResourceManager.GetString("BoundString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de marca.
        /// </summary>
        internal static string BrandCodeString {
            get {
                return ResourceManager.GetString("BrandCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de marca.
        /// </summary>
        internal static string BrandMatchingString {
            get {
                return ResourceManager.GetString("BrandMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamentos de marcas.
        /// </summary>
        internal static string BrandsMatchingString {
            get {
                return ResourceManager.GetString("BrandsMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcas.
        /// </summary>
        internal static string BrandsString {
            get {
                return ResourceManager.GetString("BrandsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        internal static string BrandString {
            get {
                return ResourceManager.GetString("BrandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo não pode conter espaços.
        /// </summary>
        internal static string CannotHaveSpacesString {
            get {
                return ResourceManager.GetString("CannotHaveSpacesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de catálogo.
        /// </summary>
        internal static string CatalogCodeString {
            get {
                return ResourceManager.GetString("CatalogCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogos.
        /// </summary>
        internal static string CatalogsString {
            get {
                return ResourceManager.GetString("CatalogsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo.
        /// </summary>
        internal static string CatalogString {
            get {
                return ResourceManager.GetString("CatalogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de categorias.
        /// </summary>
        internal static string CategoriesMatchingString {
            get {
                return ResourceManager.GetString("CategoriesMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias.
        /// </summary>
        internal static string CategoriesString {
            get {
                return ResourceManager.GetString("CategoriesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de categoria.
        /// </summary>
        internal static string CategoryMatchingString {
            get {
                return ResourceManager.GetString("CategoryMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string CategoryString {
            get {
                return ResourceManager.GetString("CategoryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemóvel.
        /// </summary>
        internal static string CellphoneString {
            get {
                return ResourceManager.GetString("CellphoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confiança estabilidade.
        /// </summary>
        internal static string CEString {
            get {
                return ResourceManager.GetString("CEString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coeficiente de estabilidade.
        /// </summary>
        internal static string CETextString {
            get {
                return ResourceManager.GetString("CETextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confiança fornecedor.
        /// </summary>
        internal static string CFString {
            get {
                return ResourceManager.GetString("CFString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coeficiente de f.
        /// </summary>
        internal static string CFTextString {
            get {
                return ResourceManager.GetString("CFTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidade.
        /// </summary>
        internal static string CityString {
            get {
                return ResourceManager.GetString("CityString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        internal static string ClassesString {
            get {
                return ResourceManager.GetString("ClassesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe.
        /// </summary>
        internal static string ClassString {
            get {
                return ResourceManager.GetString("ClassString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar.
        /// </summary>
        internal static string CleanString {
            get {
                return ResourceManager.GetString("CleanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset próximo.
        /// </summary>
        internal static string CloseResetString {
            get {
                return ResourceManager.GetString("CloseResetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        internal static string CodeString {
            get {
                return ResourceManager.GetString("CodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recolher.
        /// </summary>
        internal static string CollapseString {
            get {
                return ResourceManager.GetString("CollapseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados comerciais.
        /// </summary>
        internal static string CommercialDataString {
            get {
                return ResourceManager.GetString("CommercialDataString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string ConfigurationsString {
            get {
                return ResourceManager.GetString("ConfigurationsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Índice de preocupação no conteúdo.
        /// </summary>
        internal static string ContentConcernIndexString {
            get {
                return ResourceManager.GetString("ContentConcernIndexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo.
        /// </summary>
        internal static string ContentString {
            get {
                return ResourceManager.GetString("ContentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço de custo.
        /// </summary>
        internal static string CostPriceString {
            get {
                return ResourceManager.GetString("CostPriceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de preço de custo.
        /// </summary>
        internal static string CostPrice_DateString {
            get {
                return ResourceManager.GetString("CostPrice_DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de preço de custo U1.
        /// </summary>
        internal static string CostPrice_U1DateString {
            get {
                return ResourceManager.GetString("CostPrice_U1DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço de custo U1.
        /// </summary>
        internal static string CostPrice_U1String {
            get {
                return ResourceManager.GetString("CostPrice_U1String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de preço de custo U2.
        /// </summary>
        internal static string CostPrice_U2DateString {
            get {
                return ResourceManager.GetString("CostPrice_U2DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço de custo U2.
        /// </summary>
        internal static string CostPrice_U2String {
            get {
                return ResourceManager.GetString("CostPrice_U2String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de preço de custo U3.
        /// </summary>
        internal static string CostPrice_U3DateString {
            get {
                return ResourceManager.GetString("CostPrice_U3DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço de custo U3.
        /// </summary>
        internal static string CostPrice_U3String {
            get {
                return ResourceManager.GetString("CostPrice_U3String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação.
        /// </summary>
        internal static string CreationString {
            get {
                return ResourceManager.GetString("CreationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confiança tendência.
        /// </summary>
        internal static string CTString {
            get {
                return ResourceManager.GetString("CTString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coeficiente de t.
        /// </summary>
        internal static string CTTextString {
            get {
                return ResourceManager.GetString("CTTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotações atuais.
        /// </summary>
        internal static string CurrentQuotationsString {
            get {
                return ResourceManager.GetString("CurrentQuotationsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotaçoes atuais.
        /// </summary>
        internal static string CurrentQuotationString {
            get {
                return ResourceManager.GetString("CurrentQuotationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotações atuais.
        /// </summary>
        internal static string CurrentQuotesString {
            get {
                return ResourceManager.GetString("CurrentQuotesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atuais.
        /// </summary>
        internal static string CurrentsString {
            get {
                return ResourceManager.GetString("CurrentsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atual.
        /// </summary>
        internal static string CurrentString {
            get {
                return ResourceManager.GetString("CurrentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data reset.
        /// </summary>
        internal static string DataResetString {
            get {
                return ResourceManager.GetString("DataResetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DateString {
            get {
                return ResourceManager.GetString("DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por defeito.
        /// </summary>
        internal static string DefaultString {
            get {
                return ResourceManager.GetString("DefaultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve qualquer erro de sql, mas não foi possível eliminar registo.
        /// </summary>
        internal static string DeleteSqlErrorsString {
            get {
                return ResourceManager.GetString("DeleteSqlErrorsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string DeleteString {
            get {
                return ResourceManager.GetString("DeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição pontuação.
        /// </summary>
        internal static string DescriptionScoreString {
            get {
                return ResourceManager.GetString("DescriptionScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descontinuado.
        /// </summary>
        internal static string DiscontinuedString {
            get {
                return ResourceManager.GetString("DiscontinuedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel obter os divisores de um numero inferior a 1.
        /// </summary>
        internal static string DividersErrorString {
            get {
                return ResourceManager.GetString("DividersErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de edição.
        /// </summary>
        internal static string EditionModeString {
            get {
                return ResourceManager.GetString("EditionModeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string EditString {
            get {
                return ResourceManager.GetString("EditString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EED.
        /// </summary>
        internal static string EEDString {
            get {
                return ResourceManager.GetString("EEDString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimativa de estabilidade disponibilidade.
        /// </summary>
        internal static string EEDTextString {
            get {
                return ResourceManager.GetString("EEDTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEP.
        /// </summary>
        internal static string EEPString {
            get {
                return ResourceManager.GetString("EEPString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimativa de estabelidade preço.
        /// </summary>
        internal static string EEPTextString {
            get {
                return ResourceManager.GetString("EEPTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailString {
            get {
                return ResourceManager.GetString("EmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe, mas não está ativo.
        /// </summary>
        internal static string ExistActiveString {
            get {
                return ResourceManager.GetString("ExistActiveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe não não está inativo.
        /// </summary>
        internal static string ExistInactiveString {
            get {
                return ResourceManager.GetString("ExistInactiveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código que está a tentar inserir já existe.
        /// </summary>
        internal static string ExistingInsertCodeString {
            get {
                return ResourceManager.GetString("ExistingInsertCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validade.
        /// </summary>
        internal static string ExpirationString {
            get {
                return ResourceManager.GetString("ExpirationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas de validade.
        /// </summary>
        internal static string ExpireHoursString {
            get {
                return ResourceManager.GetString("ExpireHoursString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estender.
        /// </summary>
        internal static string ExtendString {
            get {
                return ResourceManager.GetString("ExtendString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código externo.
        /// </summary>
        internal static string ExternalCodeString {
            get {
                return ResourceManager.GetString("ExternalCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação externa.
        /// </summary>
        internal static string ExternalInformationString {
            get {
                return ResourceManager.GetString("ExternalInformationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema externo.
        /// </summary>
        internal static string ExternalSystemString {
            get {
                return ResourceManager.GetString("ExternalSystemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteristicas.
        /// </summary>
        internal static string FeaturesString {
            get {
                return ResourceManager.GetString("FeaturesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinco dias.
        /// </summary>
        internal static string FiveDayString {
            get {
                return ResourceManager.GetString("FiveDayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximo.
        /// </summary>
        internal static string ForwardString {
            get {
                return ResourceManager.GetString("ForwardString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quatro dias.
        /// </summary>
        internal static string FourDayString {
            get {
                return ResourceManager.GetString("FourDayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados gerais.
        /// </summary>
        internal static string GeneralDataString {
            get {
                return ResourceManager.GetString("GeneralDataString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        internal static string GroupString {
            get {
                return ResourceManager.GetString("GroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data superior ao permitido.
        /// </summary>
        internal static string HigherDateString {
            get {
                return ResourceManager.GetString("HigherDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotações histórico.
        /// </summary>
        internal static string HistoricalQuotesString {
            get {
                return ResourceManager.GetString("HistoricalQuotesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotações histórico.
        /// </summary>
        internal static string HistoryQuotationString {
            get {
                return ResourceManager.GetString("HistoryQuotationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeString {
            get {
                return ResourceManager.GetString("HomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas.
        /// </summary>
        internal static string HoursString {
            get {
                return ResourceManager.GetString("HoursString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD.
        /// </summary>
        internal static string ICDString {
            get {
                return ResourceManager.GetString("ICDString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Índice de confiança disponibilidade.
        /// </summary>
        internal static string ICDTextString {
            get {
                return ResourceManager.GetString("ICDTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string IconString {
            get {
                return ResourceManager.GetString("IconString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICP.
        /// </summary>
        internal static string ICPString {
            get {
                return ResourceManager.GetString("ICPString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice de confiança preço.
        /// </summary>
        internal static string ICPTextString {
            get {
                return ResourceManager.GetString("ICPTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuinte.
        /// </summary>
        internal static string IdentificationNumberString {
            get {
                return ResourceManager.GetString("IdentificationNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação.
        /// </summary>
        internal static string IdentificationString {
            get {
                return ResourceManager.GetString("IdentificationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem pontuação.
        /// </summary>
        internal static string ImageScoreString {
            get {
                return ResourceManager.GetString("ImageScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        internal static string ImageString {
            get {
                return ResourceManager.GetString("ImageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização automática da suggestão.
        /// </summary>
        internal static string InactiveAutomaticUpdateSuggestionString {
            get {
                return ResourceManager.GetString("InactiveAutomaticUpdateSuggestionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestão para a descrição inativa.
        /// </summary>
        internal static string InactiveDescriptionSuggestionString {
            get {
                return ResourceManager.GetString("InactiveDescriptionSuggestionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestão para as caracteristicas inativa.
        /// </summary>
        internal static string InactiveFeatureSuggestionString {
            get {
                return ResourceManager.GetString("InactiveFeatureSuggestionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestão para a imagem inativa.
        /// </summary>
        internal static string InactiveImageSugestionString {
            get {
                return ResourceManager.GetString("InactiveImageSugestionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestão para o link inativa.
        /// </summary>
        internal static string InactiveLinkSuggestionString {
            get {
                return ResourceManager.GetString("InactiveLinkSuggestionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        internal static string InactiveString {
            get {
                return ResourceManager.GetString("InactiveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incongruência.
        /// </summary>
        internal static string InconsistencyString {
            get {
                return ResourceManager.GetString("InconsistencyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice.
        /// </summary>
        internal static string IndexString {
            get {
                return ResourceManager.GetString("IndexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes de informação de produto disponíveis.
        /// </summary>
        internal static string InfoProductDetailAvailableString {
            get {
                return ResourceManager.GetString("InfoProductDetailAvailableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação inicial das caracteristicas.
        /// </summary>
        internal static string InicialScoreFeaturesString {
            get {
                return ResourceManager.GetString("InicialScoreFeaturesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação inicial da imagem.
        /// </summary>
        internal static string InicialScoreImageString {
            get {
                return ResourceManager.GetString("InicialScoreImageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pontuação inicial do link.
        /// </summary>
        internal static string InicialScoreLinkString {
            get {
                return ResourceManager.GetString("InicialScoreLinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação inicial da descrição.
        /// </summary>
        internal static string InitialScoreDescriptionString {
            get {
                return ResourceManager.GetString("InitialScoreDescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve qualquer erro de sql, mas não foi possível inserir registo.
        /// </summary>
        internal static string InsertSqlErrorsString {
            get {
                return ResourceManager.GetString("InsertSqlErrorsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir.
        /// </summary>
        internal static string InsertString {
            get {
                return ResourceManager.GetString("InsertString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação interna.
        /// </summary>
        internal static string InternalInformationString {
            get {
                return ResourceManager.GetString("InternalInformationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC.
        /// </summary>
        internal static string IPCString {
            get {
                return ResourceManager.GetString("IPCString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string LanguageString {
            get {
                return ResourceManager.GetString("LanguageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho de texto superior ao permitido.
        /// </summary>
        internal static string LargerTextString {
            get {
                return ResourceManager.GetString("LargerTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link pontuação.
        /// </summary>
        internal static string LinkScoreString {
            get {
                return ResourceManager.GetString("LinkScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string LinkString {
            get {
                return ResourceManager.GetString("LinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar.
        /// </summary>
        internal static string LoadString {
            get {
                return ResourceManager.GetString("LoadString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inferior ao permitido.
        /// </summary>
        internal static string LowerDateString {
            get {
                return ResourceManager.GetString("LowerDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização manual.
        /// </summary>
        internal static string ManualUpdateString {
            get {
                return ResourceManager.GetString("ManualUpdateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margem.
        /// </summary>
        internal static string MarginString {
            get {
                return ResourceManager.GetString("MarginString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamentos.
        /// </summary>
        internal static string MatchingsString {
            get {
                return ResourceManager.GetString("MatchingsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento.
        /// </summary>
        internal static string MatchingString {
            get {
                return ResourceManager.GetString("MatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço máximo permitido.
        /// </summary>
        internal static string MaxPriceAllowedString {
            get {
                return ResourceManager.GetString("MaxPriceAllowedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude máxima de preço.
        /// </summary>
        internal static string MaxPriceAmplitudeString {
            get {
                return ResourceManager.GetString("MaxPriceAmplitudeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço mínimo permitido.
        /// </summary>
        internal static string MinPriceAllowedString {
            get {
                return ResourceManager.GetString("MinPriceAllowedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemóvel.
        /// </summary>
        internal static string MobileString {
            get {
                return ResourceManager.GetString("MobileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo.
        /// </summary>
        internal static string ModeString {
            get {
                return ResourceManager.GetString("ModeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mais Informação.
        /// </summary>
        internal static string MoreInfoString {
            get {
                return ResourceManager.GetString("MoreInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preenchimento obrigatório.
        /// </summary>
        internal static string MustBeFilledString {
            get {
                return ResourceManager.GetString("MustBeFilledString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo tem que ter pelo menos um caracter numerico.
        /// </summary>
        internal static string MustHaveNumericCharString {
            get {
                return ResourceManager.GetString("MustHaveNumericCharString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to este campo tem que ter pelo menos um caracter especial.
        /// </summary>
        internal static string MustHaveSpecialCharString {
            get {
                return ResourceManager.GetString("MustHaveSpecialCharString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispensa prevenção de falso stock.
        /// </summary>
        internal static string NeedPreventionFakeStockString {
            get {
                return ResourceManager.GetString("NeedPreventionFakeStockString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispensa prevenção de preços desfasados.
        /// </summary>
        internal static string NeedPreventionPricesOutString {
            get {
                return ResourceManager.GetString("NeedPreventionPricesOutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        internal static string NewString {
            get {
                return ResourceManager.GetString("NewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem dados.
        /// </summary>
        internal static string NoDataString {
            get {
                return ResourceManager.GetString("NoDataString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        internal static string NoString {
            get {
                return ResourceManager.GetString("NoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        internal static string NotesString {
            get {
                return ResourceManager.GetString("NotesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código que está a tentar eliminar não existe.
        /// </summary>
        internal static string NotExistingDeleteCodeString {
            get {
                return ResourceManager.GetString("NotExistingDeleteCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código que está a tentar alterar não existe.
        /// </summary>
        internal static string NotExistingUpdateCodeString {
            get {
                return ResourceManager.GetString("NotExistingUpdateCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe.
        /// </summary>
        internal static string NotExistString {
            get {
                return ResourceManager.GetString("NotExistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existencia de caracteres numericos.
        /// </summary>
        internal static string NumericCharString {
            get {
                return ResourceManager.GetString("NumericCharString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um dia.
        /// </summary>
        internal static string OneDayString {
            get {
                return ResourceManager.GetString("OneDayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um mês.
        /// </summary>
        internal static string OneMonthString {
            get {
                return ResourceManager.GetString("OneMonthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma semana.
        /// </summary>
        internal static string OneWeekString {
            get {
                return ResourceManager.GetString("OneWeekString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso exterior ativo.
        /// </summary>
        internal static string OnlineActiveAccessString {
            get {
                return ResourceManager.GetString("OnlineActiveAccessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string OpenString {
            get {
                return ResourceManager.GetString("OpenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros.
        /// </summary>
        internal static string OthersString {
            get {
                return ResourceManager.GetString("OthersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnumber.
        /// </summary>
        internal static string PartnumberString {
            get {
                return ResourceManager.GetString("PartnumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordString {
            get {
                return ResourceManager.GetString("PasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string PhoneString {
            get {
                return ResourceManager.GetString("PhoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevenção de falso stock.
        /// </summary>
        internal static string PreventionFakeStockString {
            get {
                return ResourceManager.GetString("PreventionFakeStockString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevenção de preços desfasados.
        /// </summary>
        internal static string PreventionPricesOutString {
            get {
                return ResourceManager.GetString("PreventionPricesOutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço.
        /// </summary>
        internal static string PriceString {
            get {
                return ResourceManager.GetString("PriceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confiança na disponibilidade do produto.
        /// </summary>
        internal static string ProductAvailableTrustString {
            get {
                return ResourceManager.GetString("ProductAvailableTrustString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo de produto.
        /// </summary>
        internal static string ProductCodeString {
            get {
                return ResourceManager.GetString("ProductCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de Produto.
        /// </summary>
        internal static string ProductMatchingString {
            get {
                return ResourceManager.GetString("ProductMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confiança no preço do produto.
        /// </summary>
        internal static string ProductPriceTrustString {
            get {
                return ResourceManager.GetString("ProductPriceTrustString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos Matching.
        /// </summary>
        internal static string ProductsMatchingString {
            get {
                return ResourceManager.GetString("ProductsMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        internal static string ProductsString {
            get {
                return ResourceManager.GetString("ProductsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        internal static string ProductString {
            get {
                return ResourceManager.GetString("ProductString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regras de cotação.
        /// </summary>
        internal static string QuotationRulesString {
            get {
                return ResourceManager.GetString("QuotationRulesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regras de cotações.
        /// </summary>
        internal static string QuotationRuleString {
            get {
                return ResourceManager.GetString("QuotationRuleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotações.
        /// </summary>
        internal static string QuotationsString {
            get {
                return ResourceManager.GetString("QuotationsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação.
        /// </summary>
        internal static string QuotationString {
            get {
                return ResourceManager.GetString("QuotationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuotationWarningsString {
            get {
                return ResourceManager.GetString("QuotationWarningsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ran {
            get {
                return ResourceManager.GetString("Ran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de margem mínimo.
        /// </summary>
        internal static string RangeMinValueString {
            get {
                return ResourceManager.GetString("RangeMinValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margem.
        /// </summary>
        internal static string RangeString {
            get {
                return ResourceManager.GetString("RangeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nunhum registo para o filtro selecionado.
        /// </summary>
        internal static string RecordNotFoundString {
            get {
                return ResourceManager.GetString("RecordNotFoundString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias relacionadas.
        /// </summary>
        internal static string RelationCategoriesString {
            get {
                return ResourceManager.GetString("RelationCategoriesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regras.
        /// </summary>
        internal static string RulesString {
            get {
                return ResourceManager.GetString("RulesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regra.
        /// </summary>
        internal static string RuleString {
            get {
                return ResourceManager.GetString("RuleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do comercial.
        /// </summary>
        internal static string SalesmanDataString {
            get {
                return ResourceManager.GetString("SalesmanDataString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedor.
        /// </summary>
        internal static string SalesmanString {
            get {
                return ResourceManager.GetString("SalesmanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação.
        /// </summary>
        internal static string ScoreString {
            get {
                return ResourceManager.GetString("ScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        internal static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar.
        /// </summary>
        internal static string SelectString {
            get {
                return ResourceManager.GetString("SelectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravidade.
        /// </summary>
        internal static string SeverityString {
            get {
                return ResourceManager.GetString("SeverityString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seis dias.
        /// </summary>
        internal static string SixDayString {
            get {
                return ResourceManager.GetString("SixDayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamalho de texto inferior ao permitido.
        /// </summary>
        internal static string SmallerTextString {
            get {
                return ResourceManager.GetString("SmallerTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms.
        /// </summary>
        internal static string SmsString {
            get {
                return ResourceManager.GetString("SmsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existencia de espaços.
        /// </summary>
        internal static string SpaceExistenceString {
            get {
                return ResourceManager.GetString("SpaceExistenceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existencia de caracteres especiais.
        /// </summary>
        internal static string SpecialCharString {
            get {
                return ResourceManager.GetString("SpecialCharString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de Estado.
        /// </summary>
        internal static string StateMatchingString {
            get {
                return ResourceManager.GetString("StateMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de estados.
        /// </summary>
        internal static string StatesMatchingString {
            get {
                return ResourceManager.GetString("StatesMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estados.
        /// </summary>
        internal static string StatesString {
            get {
                return ResourceManager.GetString("StatesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string StateString {
            get {
                return ResourceManager.GetString("StateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatisticas.
        /// </summary>
        internal static string StatisticsString {
            get {
                return ResourceManager.GetString("StatisticsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de stock percentil 50.
        /// </summary>
        internal static string StockCodeExpirationP50String {
            get {
                return ResourceManager.GetString("StockCodeExpirationP50String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de stock percentil 60.
        /// </summary>
        internal static string StockCodeExpirationP60String {
            get {
                return ResourceManager.GetString("StockCodeExpirationP60String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de stock percentil 70.
        /// </summary>
        internal static string StockCodeExpirationP70String {
            get {
                return ResourceManager.GetString("StockCodeExpirationP70String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de stock percentil 80.
        /// </summary>
        internal static string StockCodeExpirationP80String {
            get {
                return ResourceManager.GetString("StockCodeExpirationP80String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de stock percentil 90.
        /// </summary>
        internal static string StockCodeExpirationP90String {
            get {
                return ResourceManager.GetString("StockCodeExpirationP90String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de stock.
        /// </summary>
        internal static string StockCodeString {
            get {
                return ResourceManager.GetString("StockCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de código de stock.
        /// </summary>
        internal static string StockCode_DateString {
            get {
                return ResourceManager.GetString("StockCode_DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de código de stock U1.
        /// </summary>
        internal static string StockCode_U1DateString {
            get {
                return ResourceManager.GetString("StockCode_U1DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de stock U1.
        /// </summary>
        internal static string StockCode_U1String {
            get {
                return ResourceManager.GetString("StockCode_U1String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de código de stock U2.
        /// </summary>
        internal static string StockCode_U2DateString {
            get {
                return ResourceManager.GetString("StockCode_U2DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de stock U2.
        /// </summary>
        internal static string StockCode_U2String {
            get {
                return ResourceManager.GetString("StockCode_U2String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de código de stock U3.
        /// </summary>
        internal static string StockCode_U3DateString {
            get {
                return ResourceManager.GetString("StockCode_U3DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de stock U3.
        /// </summary>
        internal static string StockCode_U3String {
            get {
                return ResourceManager.GetString("StockCode_U3String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de stock.
        /// </summary>
        internal static string StockMatchingString {
            get {
                return ResourceManager.GetString("StockMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string StockMatchingString1 {
            get {
                return ResourceManager.GetString("StockMatchingString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de stocks.
        /// </summary>
        internal static string StocksMatchingString {
            get {
                return ResourceManager.GetString("StocksMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        internal static string StocksString {
            get {
                return ResourceManager.GetString("StocksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string StockString {
            get {
                return ResourceManager.GetString("StockString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estruturas.
        /// </summary>
        internal static string StructuresString {
            get {
                return ResourceManager.GetString("StructuresString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo de stock substituto.
        /// </summary>
        internal static string SubstituteStockCodeString {
            get {
                return ResourceManager.GetString("SubstituteStockCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock substituto.
        /// </summary>
        internal static string SubstituteStockString {
            get {
                return ResourceManager.GetString("SubstituteStockString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestão de horas de validade.
        /// </summary>
        internal static string SuggestionExpireHoursString {
            get {
                return ResourceManager.GetString("SuggestionExpireHoursString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de complemento.
        /// </summary>
        internal static string SupplementMatchingString {
            get {
                return ResourceManager.GetString("SupplementMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de complementos.
        /// </summary>
        internal static string SupplementsMatchingString {
            get {
                return ResourceManager.GetString("SupplementsMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complementos.
        /// </summary>
        internal static string SupplementsString {
            get {
                return ResourceManager.GetString("SupplementsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        internal static string SupplementString {
            get {
                return ResourceManager.GetString("SupplementString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação inicial para qualidade das caracteristicas do produto.
        /// </summary>
        internal static string SupplierBigText10String {
            get {
                return ResourceManager.GetString("SupplierBigText10String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação inicial para qualidade da imagem do produto.
        /// </summary>
        internal static string SupplierBigText11String {
            get {
                return ResourceManager.GetString("SupplierBigText11String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação inicial para qualidade do link do produto.
        /// </summary>
        internal static string SupplierBigText12String {
            get {
                return ResourceManager.GetString("SupplierBigText12String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível de confiança no preço dos produtos.
        /// </summary>
        internal static string SupplierBigText13String {
            get {
                return ResourceManager.GetString("SupplierBigText13String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível de confiança na disponibilidade dos produtos.
        /// </summary>
        internal static string SupplierBigText14String {
            get {
                return ResourceManager.GetString("SupplierBigText14String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite atualização automática da informação de produtos.
        /// </summary>
        internal static string SupplierBigText15String {
            get {
                return ResourceManager.GetString("SupplierBigText15String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas de validade, sugestão para novas regras de cotações.
        /// </summary>
        internal static string SupplierBigText1String {
            get {
                return ResourceManager.GetString("SupplierBigText1String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite execução automática de mapeamento de produtos.
        /// </summary>
        internal static string SupplierBigText2String {
            get {
                return ResourceManager.GetString("SupplierBigText2String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite criação automática de novos produtos.
        /// </summary>
        internal static string SupplierBigText3String {
            get {
                return ResourceManager.GetString("SupplierBigText3String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibiliza informação de produtos publicamente.
        /// </summary>
        internal static string SupplierBigText4String {
            get {
                return ResourceManager.GetString("SupplierBigText4String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite importação de descrição de produtos.
        /// </summary>
        internal static string SupplierBigText5String {
            get {
                return ResourceManager.GetString("SupplierBigText5String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite importação de caracteristicas de produtos.
        /// </summary>
        internal static string SupplierBigText6String {
            get {
                return ResourceManager.GetString("SupplierBigText6String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite importação de link de produto.
        /// </summary>
        internal static string SupplierBigText7String {
            get {
                return ResourceManager.GetString("SupplierBigText7String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite importação de imagem de produto.
        /// </summary>
        internal static string SupplierBigText8String {
            get {
                return ResourceManager.GetString("SupplierBigText8String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação inicial para qualidade da descrição de produtos.
        /// </summary>
        internal static string SupplierBigText9String {
            get {
                return ResourceManager.GetString("SupplierBigText9String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confianca fornecedor marca.
        /// </summary>
        internal static string SupplierBrandTrustString {
            get {
                return ResourceManager.GetString("SupplierBrandTrustString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de fornecedor.
        /// </summary>
        internal static string SupplierCodeString {
            get {
                return ResourceManager.GetString("SupplierCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedores.
        /// </summary>
        internal static string SuppliersString {
            get {
                return ResourceManager.GetString("SuppliersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor.
        /// </summary>
        internal static string SupplierString {
            get {
                return ResourceManager.GetString("SupplierString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhereToBuy.
        /// </summary>
        internal static string SystemBrandString {
            get {
                return ResourceManager.GetString("SystemBrandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelas.
        /// </summary>
        internal static string TablesString {
            get {
                return ResourceManager.GetString("TablesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designação fiscal.
        /// </summary>
        internal static string TaxDesignationString {
            get {
                return ResourceManager.GetString("TaxDesignationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamentos de impostos.
        /// </summary>
        internal static string TaxesMatchingString {
            get {
                return ResourceManager.GetString("TaxesMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostos.
        /// </summary>
        internal static string TaxesString {
            get {
                return ResourceManager.GetString("TaxesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de imposto.
        /// </summary>
        internal static string TaxMatchingString {
            get {
                return ResourceManager.GetString("TaxMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa.
        /// </summary>
        internal static string TaxRateString {
            get {
                return ResourceManager.GetString("TaxRateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposto.
        /// </summary>
        internal static string TaxString {
            get {
                return ResourceManager.GetString("TaxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do imposto.
        /// </summary>
        internal static string TaxValueString {
            get {
                return ResourceManager.GetString("TaxValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termo.
        /// </summary>
        internal static string TermString {
            get {
                return ResourceManager.GetString("TermString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto a adicionar.
        /// </summary>
        internal static string TextToAddString {
            get {
                return ResourceManager.GetString("TextToAddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto a remover.
        /// </summary>
        internal static string TextToRemoveString {
            get {
                return ResourceManager.GetString("TextToRemoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Três dias.
        /// </summary>
        internal static string ThreeDayString {
            get {
                return ResourceManager.GetString("ThreeDayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Três semanas.
        /// </summary>
        internal static string ThreeWeekString {
            get {
                return ResourceManager.GetString("ThreeWeekString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Índice de confianca.
        /// </summary>
        internal static string TrustIndexString {
            get {
                return ResourceManager.GetString("TrustIndexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confiança.
        /// </summary>
        internal static string TrustString {
            get {
                return ResourceManager.GetString("TrustString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dois dias.
        /// </summary>
        internal static string TwoDayString {
            get {
                return ResourceManager.GetString("TwoDayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dois meses.
        /// </summary>
        internal static string TwoMonthString {
            get {
                return ResourceManager.GetString("TwoMonthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duas semanas.
        /// </summary>
        internal static string TwoWeekString {
            get {
                return ResourceManager.GetString("TwoWeekString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento de produtos automático.
        /// </summary>
        internal static string txtSupplierProductMatchingString {
            get {
                return ResourceManager.GetString("txtSupplierProductMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string TypeString {
            get {
                return ResourceManager.GetString("TypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso médio por unidade.
        /// </summary>
        internal static string UnityWeightAverageString {
            get {
                return ResourceManager.GetString("UnityWeightAverageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve qualquer erro de sql, mas não foi possível alterar registo.
        /// </summary>
        internal static string UpdateSqlErrorsString {
            get {
                return ResourceManager.GetString("UpdateSqlErrorsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        internal static string UpdateString {
            get {
                return ResourceManager.GetString("UpdateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UsernameString {
            get {
                return ResourceManager.GetString("UsernameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador.
        /// </summary>
        internal static string UserString {
            get {
                return ResourceManager.GetString("UserString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão.
        /// </summary>
        internal static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avisos.
        /// </summary>
        internal static string WarningsString {
            get {
                return ResourceManager.GetString("WarningsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        internal static string WarningString {
            get {
                return ResourceManager.GetString("WarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avisos tipo.
        /// </summary>
        internal static string WarningTypesString {
            get {
                return ResourceManager.GetString("WarningTypesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso tipo.
        /// </summary>
        internal static string WarningTypeString {
            get {
                return ResourceManager.GetString("WarningTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com personalização.
        /// </summary>
        internal static string WithCustomizationString {
            get {
                return ResourceManager.GetString("WithCustomizationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com personalização.
        /// </summary>
        internal static string WithCustomString {
            get {
                return ResourceManager.GetString("WithCustomString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem mapeamento.
        /// </summary>
        internal static string WithoutMatchingString {
            get {
                return ResourceManager.GetString("WithoutMatchingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termos preocupantes.
        /// </summary>
        internal static string WorryingTermsString {
            get {
                return ResourceManager.GetString("WorryingTermsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termo preocupante.
        /// </summary>
        internal static string WorryingTermString {
            get {
                return ResourceManager.GetString("WorryingTermString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string YesString {
            get {
                return ResourceManager.GetString("YesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código postal.
        /// </summary>
        internal static string ZipCodeString {
            get {
                return ResourceManager.GetString("ZipCodeString", resourceCulture);
            }
        }
    }
}
