//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereToBuy.web.App.Products.Product {
    
    
    public partial class Product {
        
        /// <summary>
        /// ProductUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WhereToBuy.web.UserControls.Products.Product.ProductUC ProductUC;
    }
}
